### PR TITLE
make repo react compatible

### PR DESCRIPTION
**Pull request by mehul1409**
Make the repository React-compatible and maintain the responsiveness of the website, excluding the subscribe section.

### CODE REVIEW

**Comment by mendacium-a11y** [comment]
could you also migrate from vanilla css to tailwind

**Comment by exitflynn** [comment]
Yo thanks @mendacium-a11y, we can have a separate issue for that with room for comments from others. 
For now can you or @osdc/2023-24 take a look at the PR and make sure it's doing what's intended and we don't need to change anything before merging?

**Review by mendacium-a11y — COMMENTED** [review]
looks good!!

**Comment by exitflynn** [comment]
LGTM too, can ye merge @mendacium-a11y

**Comment by exitflynn** [comment]
letsgoo, thanks @mehul1409!! :partying_face:

**Pull request merged**
