### PR TITLE
integrate tailwind css

### PR DESCRIPTION
**Pull request by mehul1409**
made complete responsive website using tailwind css

### CODE REVIEW

**Comment by mehul1409** [comment]
working on animation now

**Comment by shivang0-0** [comment]
> @shivang0-0  @madhavmehndiratta @mendacium-a11y 
> Can you please look at this PR 

We can omit the navebar for now, feels of no use for a not so long landing page.

**Comment by madhavmehndiratta** [comment]
Change the title to OSDC and I think we are good to go.

**Comment by mendacium-a11y** [comment]
maybe add the `<title>` tag in `<html>` and an icon as well

**Comment by mehul1409** [comment]
Done 
@mendacium-a11y

**Pull request merged**
